wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.13
    cli_version: 0.28.0
    framework: huggingface
    huggingface_version: 5.13.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1785423581
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 80
      - 103
      3:
      - 2
      - 4
      - 13
      - 16
      - 37
      - 42
      4: 3.12.13
      5: 0.28.0
      6: 5.13.0
      8:
      - 3
      10:
      - 20
      13: windows-amd64
    e:
      84749qyntgjvamlilof6nhzxst7sxz84:
        os: Windows-11-10.0.26200-SP0
        python: CPython 3.12.13
        started_at: '2026-07-30T14:59:38.307759Z'
        args:
        - --model
        - dinov3/vitt16
        - --backend
        - lightly
        - --decoder
        - rtdetrv2
        - --backbone-freeze
        - 'False'
        - --epochs
        - '100'
        - --seed
        - '42'
        - --raw-steps
        - --workers
        - '0'
        - --batch
        - '8'
        - --wandb-offline
        - --resume-interrupted
        program: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\run_training.py
        code_path: run_training.py
        code_path_local: run_training.py
        git:
          remote_url: https://github.com/Brezemil/_trainer_lightly.git
          commit: 08c106817e0acfeae01ecd94b831687615a3f310
        root: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\wandb
        host: CF-LILA-004-D
        executable: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\.pixi\envs\default\python.exe
        cpu_count: 16
        cpu_count_logical: 32
        gpu_type: NVIDIA GeForce RTX 5080
        gpu_count: 1
        disk:
          /:
            total: '3999134642176'
            used: '309120655360'
        memory:
          total: '66207113216'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 5080
          memory_total: '17094934528'
          cuda_cores: 10752
          architecture: Blackwell
          uuid: GPU-1f2177d1-9609-f5c5-c288-200e2c2f74a2
        cuda_version: '13.3'
        writer_id: 84749qyntgjvamlilof6nhzxst7sxz84
model:
  desc: null
  value: dinov3/vitt16-ltdetr
seed:
  desc: null
  value: 42
epochs:
  desc: null
  value: 100
imgsz:
  desc: null
  value: 1024
batch_size:
  desc: null
  value: 8
device:
  desc: null
  value: 0
workers:
  desc: null
  value: 0
fraction:
  desc: null
  value: 1.0
runs_dir:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\runs
wandb_dir:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\wandb
dataset:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_dataset_ail\dataset.yaml
backend:
  desc: null
  value: lightly
decoder_name:
  desc: null
  value: rtdetrv2
out:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\runs\dinov3/vitt16_seed_42_rtdetrv2_steps_17354
data:
  desc: null
  value:
    format: yolo
    path: C:\Users\emil_brezovsky\Documents\GitHub\_dataset_ail
    train: train\images
    val: val\images
    test: test/images
    names:
      '0': A. altissima
    ignore_classes: null
    skip_if_label_file_missing: false
task:
  desc: null
  value: object_detection
steps:
  desc: null
  value: 17354
num_workers:
  desc: null
  value: 0
devices:
  desc: null
  value:
  - 0
num_nodes:
  desc: null
  value: 1
checkpoint:
  desc: null
  value: null
reuse_class_head:
  desc: null
  value: false
accelerator:
  desc: null
  value: CUDAAccelerator
strategy:
  desc: null
  value: SingleDeviceStrategy
precision:
  desc: null
  value: bf16-mixed
float32_matmul_precision:
  desc: null
  value: high
logger_args:
  desc: null
  value:
    log_every_num_steps: 100
    val_every_num_steps: 1000
    val_log_every_num_steps: 20
    mlflow: null
    tensorboard:
      name: ''
      version: ''
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
    wandb:
      name: dinov3/vitt16_seed_42_rtdetrv2_steps_17354
      version: null
      offline: false
      anonymous: null
      project: _baseline
      log_model: false
      prefix: ''
      checkpoint_name: null
model_args:
  desc: null
  value:
    backbone_weights: null
    backbone_url: ''
    backbone_args: {}
    patch_size: 16
    backbone_freeze: false
    decoder_name: rtdetrv2
    use_ema_model: true
    ema_momentum: 0.9999
    ema_warmup_steps: 2000
    matcher_weight_dict:
      cost_class: 2.0
      cost_bbox: 5.0
      cost_giou: 2.0
    matcher_use_focal_loss: true
    matcher_alpha: 0.25
    matcher_gamma: 2.0
    loss_weight_dict:
      loss_vfl: 1.0
      loss_bbox: 5.0
      loss_giou: 2.0
    losses:
    - vfl
    - boxes
    loss_alpha: 0.75
    loss_gamma: 2.0
    gradient_clip_val: 0.1
    lr: 0.001
    weight_decay: 0.0001
    optimizer_betas:
    - 0.9
    - 0.999
    backbone_lr_factor: 0.05
    scheduler_name: flat-cosine
    scheduler_start_factor: 0.01
    lr_warmup_steps: 694
    scheduler_flat_steps: 9369
    scheduler_no_aug_steps: 2082
    effective_loss_weight_dict:
      loss_vfl: 1.0
      loss_bbox: 5.0
      loss_giou: 2.0
    effective_losses:
    - vfl
    - boxes
transform_args:
  desc: null
  value:
    image_size:
    - 1024
    - 1024
metric_args:
  desc: null
  value:
    watch_metric: val_metric/map
    classwise: false
    train: false
    map:
      iou_thresholds: null
      rec_thresholds: null
      max_detection_thresholds: null
      average: macro
      backend: pycocotools
loader_args:
  desc: null
  value: null
save_checkpoint_args:
  desc: null
  value:
    save_every_num_steps: 1000
    save_last: true
    save_best: true
torch_compile_args:
  desc: null
  value:
    disable: true
gradient_accumulation_steps:
  desc: null
  value: 4
resume_interrupted:
  desc: null
  value: true
