_wandb:
    value:
        cli_version: 0.28.0
        e:
            n3eeb7lrlve4w642ltwzb4wnynrctl1c:
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.3"
                disk:
                    /:
                        total: "3999134642176"
                        used: "306903785472"
                email: e.brezovsky@students.boku.ac.at
                executable: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\.pixi\envs\default\python.exe
                git:
                    commit: 08c106817e0acfeae01ecd94b831687615a3f310
                    remote: https://github.com/Brezemil/_trainer_lightly.git
                gpu: NVIDIA GeForce RTX 5080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10752
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080
                      uuid: GPU-1f2177d1-9609-f5c5-c288-200e2c2f74a2
                host: CF-LILA-004-D
                memory:
                    total: "66207113216"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\run_sweep.py
                python: CPython 3.12.13
                root: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly
                startedAt: "2026-08-02T00:41:36.872908Z"
                writerId: n3eeb7lrlve4w642ltwzb4wnynrctl1c
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 41
                - 49
                - 80
            "2":
                - 1
                - 41
                - 49
                - 80
            "3":
                - 2
                - 14
                - 61
            "4": 3.12.13
            "5": 0.28.0
            "8":
                - 3
            "12": 0.28.0
            "13": windows-amd64
        visualize:
            curves/F1-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: F1-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: F1
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/F1-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Recall(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall(B)
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Recall(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Recall-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Recall-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Recall
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Recall-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
albu_color_p:
    value: 0.3539667383815646
albu_crop_p:
    value: 0.32211824808094724
albu_dropout_p:
    value: 0.10279810197437617
albu_noise_p:
    value: 0.2028719516506033
albu_rotate90_p:
    value: 0.8086266689717938
albu_spatial_p:
    value: 0.6289893997693985
albu_texture_p:
    value: 0.17180497462125144
albu_warp_p:
    value: 0.06957280411756726
copy_paste:
    value: 0.05105502367670089
fraction:
    value: 0.5
mixup:
    value: 0
model_variant:
    value: yolo12s.pt
mosaic:
    value: 0.6826574166422319
phase:
    value: augmentation
