_wandb:
    value:
        cli_version: 0.27.2
        e:
            b6nid7t0mm6xflgnv6lg3i867gbfmui2:
                args:
                    - --model
                    - rtdetr-l.pt
                    - --seed
                    - "999"
                    - --backend
                    - ultralytics
                    - --runs-dir
                    - C:\Users\photo10\Documents\GitHub\_trainer_lightly\runs\baseline
                    - --eval-results-dir
                    - C:\Users\photo10\Documents\GitHub\_trainer_lightly\evaluation_results\baseline
                codePath: run_training.py
                codePathLocal: run_training.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "499182989312"
                        used: "443707314176"
                email: e.brezovsky@students.boku.ac.at
                executable: C:\Users\photo10\Documents\GitHub\_trainer_lightly\.pixi\envs\default\python.exe
                gpu: NVIDIA RTX A4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-6b9d4a4d-9cc4-a6a7-7274-32ede7a22372
                host: OEKB-IGEO-040-D
                memory:
                    total: "136523747328"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\photo10\Documents\GitHub\_trainer_lightly\run_training.py
                python: CPython 3.12.13
                root: C:\Users\photo10\Documents\GitHub\_trainer_lightly
                startedAt: "2026-07-26T09:42:23.892242Z"
                writerId: b6nid7t0mm6xflgnv6lg3i867gbfmui2
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 80
                - 103
            "3":
                - 2
                - 5
                - 14
                - 62
            "4": 3.12.13
            "5": 0.27.2
            "6": 5.12.1
            "8":
                - 3
            "12": 0.27.2
            "13": windows-amd64
        visualize:
            curves/F1-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: F1-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: F1
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/F1-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Recall(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall(B)
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Recall(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Recall-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Recall-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Recall
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Recall-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
backend:
    value: ultralytics
batch_size:
    value: 4
dataset:
    value: C:\Users\photo10\Documents\GitHub\_dataset_ail\dataset.yaml
device:
    value: 0
epochs:
    value: 300
fraction:
    value: 1
imgsz:
    value: 1024
model:
    value: rtdetr-l.pt
patience:
    value: 100
runs_dir:
    value: C:\Users\photo10\Documents\GitHub\_trainer_lightly\runs\baseline
seed:
    value: 999
wandb_dir:
    value: C:\Users\photo10\Documents\GitHub\_trainer_lightly\wandb
workers:
    value: 0
