wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.13
    cli_version: 0.28.0
    framework: huggingface
    huggingface_version: 5.13.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1784177738
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 80
      - 103
      3:
      - 4
      - 13
      - 16
      - 37
      - 42
      4: 3.12.13
      5: 0.28.0
      6: 5.13.0
      8:
      - 3
      10:
      - 20
      13: windows-amd64
    e:
      mfmr3lectibrswsjcsvuwv1d68lvks8n:
        os: Windows-11-10.0.26200-SP0
        python: CPython 3.12.13
        started_at: '2026-07-16T04:55:37.951897Z'
        args:
        - --model
        - dinov3/vitt16
        - --backend
        - lightly
        - --decoder
        - dfine
        - --backbone-freeze
        - 'True'
        - --workers
        - '0'
        - --batch
        - '8'
        - --wandb-offline
        - --raw-steps
        - --epochs
        - '200'
        program: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\run_training.py
        code_path: run_training.py
        code_path_local: run_training.py
        git:
          remote_url: https://github.com/Brezemil/_trainer_lightly.git
          commit: a64c032348862cb0754e5dcfbebebb5111633e3f
        root: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\wandb
        host: CF-LILA-004-D
        executable: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\.pixi\envs\default\python.exe
        cpu_count: 16
        cpu_count_logical: 32
        gpu_type: NVIDIA GeForce RTX 5080
        gpu_count: 1
        disk:
          /:
            total: '3999134642176'
            used: '279490392064'
        memory:
          total: '66207113216'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 5080
          memory_total: '17094934528'
          cuda_cores: 10752
          architecture: Blackwell
          uuid: GPU-1f2177d1-9609-f5c5-c288-200e2c2f74a2
        cuda_version: '12.9'
        writer_id: mfmr3lectibrswsjcsvuwv1d68lvks8n
model:
  desc: null
  value: dinov3/vitt16
seed:
  desc: null
  value: 100
epochs:
  desc: null
  value: 200
imgsz:
  desc: null
  value: 1024
batch_size:
  desc: null
  value: 8
device:
  desc: null
  value: 0
workers:
  desc: null
  value: 0
fraction:
  desc: null
  value: 1.0
runs_dir:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\runs
wandb_dir:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_trainer_lightly\wandb
dataset:
  desc: null
  value: C:\Users\emil_brezovsky\Documents\GitHub\_dataset_ail\dataset.yaml
backend:
  desc: null
  value: lightly
decoder_name:
  desc: null
  value: dfine
